[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/mehdifarsi/grenat"
rust-version = "1.88"

[workspace.dependencies]
grenat_lexer = { path = "crates/grenat_lexer" }
grenat_ast = { path = "crates/grenat_ast" }
grenat_parser = { path = "crates/grenat_parser" }

[profile.release]
lto = "thin"
codegen-units = 1
