[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/itsmedit/grenat"
rust-version = "1.88"

[workspace.dependencies]
grenat_lexer = { path = "crates/grenat_lexer" }
grenat_ast = { path = "crates/grenat_ast" }
grenat_parser = { path = "crates/grenat_parser" }
grenat_llm = { path = "crates/grenat_llm" }
grenat_interp = { path = "crates/grenat_interp" }
grenat_types = { path = "crates/grenat_types" }
grenat_codegen = { path = "crates/grenat_codegen" }
serde_json = "1"
ureq = { version = "3", features = ["json"] }

[profile.release]
lto = "thin"
codegen-units = 1
