[package]
name = "grenat_macros"
description = "Grenat macros: compile-time templates expanded into declarations"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
grenat_ast.workspace = true
grenat_parser.workspace = true

[dev-dependencies]
grenat_types.workspace = true
