[package]
name = "grenat_interp"
description = "Interpreter and concurrent runtime for the Grenat language"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
grenat_ast.workspace = true
grenat_llm.workspace = true
grenat_codegen.workspace = true
grenat_runtime.workspace = true
grenat_green.workspace = true
serde_json.workspace = true
ureq.workspace = true
grenat_db.workspace = true

[dev-dependencies]
grenat_parser.workspace = true
serde_json.workspace = true
