[package]
name = "grenat_driver"
description = "Loading and running Grenat programs, shared by the CLI and built executables"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
grenat_ast.workspace = true
grenat_parser.workspace = true
grenat_types.workspace = true
grenat_interp.workspace = true
grenat_lexer.workspace = true
