//! Bridge facets end to end: the fixtures `texts` (Ruby) and `numbers`
//! (Python) installed — their servers describe themselves, their
//! declarations are written — then called: results, errors, a death and a
//! restart, a timeout, and the network cut off.
//!
//! A test whose interpreter is not installed says so and returns.

use std::sync::{Arc, Mutex};
use std::time::{Duration, Instant};

use grenat_bridge::fixture::{self, PYTHON, RUBY};
use grenat_bridge::layout::Layout;
use grenat_bridge::{Installed, Log, Registry};
use grenat_native::Outcome;
use serde_json::{Value as Json, json};

fn registry(facet: &str) -> Option<Registry> {
    let (_, installed) = fixture::installed(facet)?;
    Some(Registry::new(std::slice::from_ref(installed), None))
}

/// A registry whose servers log into the returned buffer.
fn logging(installed: Installed) -> (Registry, Arc<Mutex<String>>) {
    let logged = Arc::new(Mutex::new(String::new()));
    let sink = logged.clone();
    let log: Log = Arc::new(move |line: &str| sink.lock().unwrap().push_str(line));
    (Registry::new(&[installed], Some(log)), logged)
}

fn call(registry: &Registry, name: &str, args: Json) -> Outcome {
    registry.call(name, args.to_string().as_bytes()).unwrap_or_else(|e| panic!("`{name}`: {e}"))
}

fn returned(registry: &Registry, name: &str, args: Json) -> Json {
    match call(registry, name, args) {
        Outcome::Returned(json) => json,
        other => panic!("`{name}`: {other:?}"),
    }
}

fn temp_dir(name: &str) -> std::path::PathBuf {
    let dir = std::env::temp_dir().join(format!("grenat-bridge-tests-{}-{name}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).unwrap();
    dir
}

#[test]
fn a_ruby_server_describes_itself_as_native_declarations() {
    let Some(text) = fixture::declarations(RUBY) else { return };
    for line in [
        "# Generated by setter from the bridge of the facet `texts`: do not edit.\n",
        "## A word of a text.\nstruct Word\n  text: String\n  position: Int\nend\n",
        "## The text, in capitals.\nnative def shout(text: String) -> ~String\n",
        "## Adds two integers.\nnative def add(a: Int, b: Int) -> Int pure\n",
        "native def words(text: String) -> Array(Word) pure\n",
        "native def first_word(text: String) -> String? pure\n",
        "native def count(text: String) -> Hash(String, Int) pure\n",
        "native def read_text(path: String) -> ~String uses fs.read\n",
        "native def refuse(reason: String)\n",
        "native def nap(seconds: Float)\n",
        "native def greeting -> ~String?\n",
    ] {
        assert!(text.contains(line), "{line}\nnot in:\n{text}");
    }
    let parsed = grenat_parser::parse(&text);
    assert!(parsed.diagnostics.is_empty(), "{:?}", parsed.diagnostics);
    let (dir, installed) = fixture::installed(RUBY).unwrap();
    assert_eq!(installed.manifest.function("read_text").unwrap().error, "TextError");
    assert!(Layout::new(dir).manifest().is_file());
    assert_eq!(Installed::read(RUBY, dir, &installed.spec).unwrap(), *installed);
}

#[test]
fn a_python_server_describes_itself_from_its_annotations() {
    let Some(text) = fixture::declarations(PYTHON) else { return };
    for line in [
        "## A point of the plane.\nstruct Point\n  x: Float\n  y: Float\nend\n",
        "## The mean of the values, if there are some.\nnative def mean(values: Array(Float)) -> Float? pure\n",
        "native def add(a: Int, b: Int) -> Int pure\n",
        "native def histogram(values: Array(Int)) -> Hash(String, Int) pure\n",
        "native def middle(a: Point, b: Point) -> Point pure\n",
        "native def ratio(a: Float, b: Float) -> ~Float\n",
        "native def fetch(port: Int) -> ~String uses net\n",
        "native def crash(status: Int)\n",
    ] {
        assert!(text.contains(line), "{line}\nnot in:\n{text}");
    }
    assert!(grenat_parser::parse(&text).diagnostics.is_empty());
}

#[test]
fn ruby_functions_are_called_with_json() {
    let Some(texts) = registry(RUBY) else { return };
    assert_eq!(returned(&texts, "shout", json!(["hi"])), json!("HI"));
    assert_eq!(returned(&texts, "add", json!([40, 2])), json!(42));
    assert_eq!(
        returned(&texts, "words", json!(["a bb"])),
        json!([{"text": "a", "position": 0}, {"text": "bb", "position": 1}])
    );
    assert_eq!(returned(&texts, "first_word", json!([""])), Json::Null);
    assert_eq!(returned(&texts, "count", json!(["a b a"])), json!({"a": 2, "b": 1}));
}

#[test]
fn python_functions_are_called_with_json() {
    let Some(numbers) = registry(PYTHON) else { return };
    assert_eq!(returned(&numbers, "mean", json!([[1.0, 2.0]])), json!(1.5));
    assert_eq!(returned(&numbers, "mean", json!([[]])), Json::Null);
    assert_eq!(returned(&numbers, "add", json!([40, 2])), json!(42));
    assert_eq!(returned(&numbers, "histogram", json!([[1, 2, 1]])), json!({"1": 2, "2": 1}));
    assert_eq!(
        returned(&numbers, "middle", json!([{"x": 0.0, "y": 0.0}, {"x": 2.0, "y": 4.0}])),
        json!({"x": 1.0, "y": 2.0})
    );
}

#[test]
fn errors_name_their_grenat_type() {
    let raised = |registry: &Registry, name: &str, args: Json| match call(registry, name, args) {
        Outcome::Raised { ty, message } => (ty, message),
        other => panic!("`{name}`: {other:?}"),
    };
    if let Some(texts) = registry(RUBY) {
        assert_eq!(raised(&texts, "refuse", json!(["no"])), ("Refused".into(), "no".into()));
        let (ty, message) = raised(&texts, "read_text", json!(["/nowhere/at/all"]));
        assert_eq!(ty, "TextError");
        assert!(message.contains("/nowhere/at/all"), "{message}");
        let (ty, message) = raised(&texts, "add", json!([1]));
        assert_eq!((ty.as_str(), message.as_str()), ("BridgeError", "`add` takes 2 argument(s)"));
        // the server still answers
        assert_eq!(returned(&texts, "add", json!([1, 1])), json!(2));
    }
    if let Some(numbers) = registry(PYTHON) {
        assert_eq!(raised(&numbers, "odd", json!([2])), ("NotOdd".into(), "2 is even".into()));
        let (ty, message) = raised(&numbers, "ratio", json!([1.0, 0.0]));
        assert_eq!(ty, "MathError");
        assert!(message.contains("division by zero"), "{message}");
        assert_eq!(returned(&numbers, "odd", json!([3])), json!(3));
    }
    let e = Registry::default().call("shout", b"[]").unwrap_err();
    assert_eq!(e, "no bridge provides `shout`: install the facet that declares it (`setter install`)");
}

#[test]
fn a_server_is_kept_alive_and_started_again_when_it_dies() {
    for (facet, die) in [(RUBY, "die"), (PYTHON, "crash")] {
        let Some((_, installed)) = fixture::installed(facet) else { continue };
        let (registry, logged) = logging(installed.clone());
        let pid = returned(&registry, "pid", json!([]));
        assert_eq!(returned(&registry, "pid", json!([])), pid, "{facet}: one process for every call");
        // a call with effects is never sent twice: it fails, with the server's last words
        let e = registry.call(die, b"[3]").unwrap_err();
        assert!(e.starts_with(&format!("the process of facet `{facet}` exited with status 3:")), "{e}");
        assert!(e.ends_with(&format!("(during `{die}`)")), "{e}");
        assert!(e.contains(if facet == RUBY { "dying" } else { "crashing" }), "{e}");
        // the next call starts a new server
        let again = returned(&registry, "pid", json!([]));
        assert_ne!(again, pid, "{facet}");
        drop(registry);
        let logged = logged.lock().unwrap().clone();
        let line = if facet == RUBY { "[bridge] texts: dying\n" } else { "[bridge] numbers: crashing\n" };
        assert!(logged.contains(line), "{logged}");
    }
}

#[test]
fn a_pure_call_is_sent_again_to_a_new_server() {
    let Some(texts) = registry(RUBY) else { return };
    let marker = temp_dir("flaky").join("marker");
    assert_eq!(returned(&texts, "flaky", json!([marker.to_string_lossy()])), json!("recovered"));
    assert!(marker.is_file());
}

#[test]
fn a_call_that_runs_too_long_is_stopped() {
    let Some((_, installed)) = fixture::installed(RUBY) else { return };
    let mut quick = installed.clone();
    quick.spec.timeout = Duration::from_millis(500);
    let (registry, _) = logging(quick);
    let pid = returned(&registry, "pid", json!([]));
    let started = Instant::now();
    let e = registry.call("nap", b"[30.0]").unwrap_err();
    assert_eq!(e, "`nap` still running after 500ms: the process of facet `texts` was killed");
    assert!(started.elapsed() < Duration::from_secs(10));
    assert_ne!(returned(&registry, "pid", json!([])), pid);
}

#[test]
fn standard_output_is_the_protocols_and_standard_error_the_logs() {
    let Some((_, installed)) = fixture::installed(RUBY) else { return };
    let (registry, logged) = logging(installed.clone());
    assert_eq!(returned(&registry, "chatter", json!(["x"])), json!("x"));
    drop(registry);
    let logged = logged.lock().unwrap().clone();
    assert!(logged.contains("[bridge] texts: printed x\n"), "{logged}");
    assert!(logged.contains("[bridge] texts: warned x\n"), "{logged}");
}

#[test]
fn the_environment_is_clean_but_for_declared_variables() {
    let Some(texts) = registry(RUBY) else { return };
    // cargo sets it for the tests: not passed on
    assert!(std::env::var("CARGO_PKG_NAME").is_ok());
    assert_eq!(returned(&texts, "variable", json!(["CARGO_PKG_NAME"])), Json::Null);
    assert_eq!(returned(&texts, "variable", json!(["PATH"])), json!(std::env::var("PATH").unwrap()));
    assert!(returned(&texts, "variable", json!(["RUBYLIB"])).as_str().unwrap().ends_with(".grenat/bridge/lib/ruby"));
    // declared, it would be passed on if set (see grenat_cli's tests)
    assert_eq!(returned(&texts, "greeting", json!([])), json!(std::env::var("TEXTS_GREETING").ok()));
}

#[test]
fn the_network_is_cut_off_unless_a_function_declares_it() {
    let listener = std::net::TcpListener::bind("127.0.0.1:0").unwrap();
    let port = listener.local_addr().unwrap().port();
    std::thread::spawn(move || {
        use std::io::Write;
        for mut stream in listener.incoming().flatten() {
            let _ = stream.write_all(b"hello");
        }
    });
    // `numbers` declares `net` (its `fetch`): its server has the network
    if let Some(numbers) = registry(PYTHON) {
        assert_eq!(returned(&numbers, "fetch", json!([port])), json!("hello"));
    }
    // `texts` does not: its server cannot connect, where the sandbox works
    let Some((_, installed)) = fixture::installed(RUBY) else { return };
    let (texts, logged) = logging(installed.clone());
    let connected = returned(&texts, "connect", json!([port]));
    match grenat_sandbox::isolation_works() {
        Ok(()) => assert_eq!(connected, json!(false)),
        Err(why) => {
            println!("skipped: the sandbox does not work here ({why}): the network cannot be cut off");
            assert_eq!(connected, json!(true));
            drop(texts);
            assert!(logged.lock().unwrap().contains("[bridge] texts: no network isolation here"));
        }
    }
}
