[package]
name = "grenat_codegen"
description = "Native code generation for Grenat (Cranelift JIT)"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
grenat_ast.workspace = true
grenat_runtime.workspace = true
cranelift-codegen = "0.136"
cranelift-frontend = "0.136"
cranelift-jit = "0.136"
cranelift-module = "0.136"
cranelift-native = "0.136"
cranelift-object = "0.136"

[dev-dependencies]
grenat_parser.workspace = true
grenat_runtime.workspace = true
