[package]
name = "grenat_types"
description = "Static checking for Grenat: names, types, effects and taint"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
grenat_ast.workspace = true

[dev-dependencies]
grenat_parser.workspace = true
