[package]
name = "grenat_types"
description = "Vérification statique de Grenat : noms, types, effets et teinte"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
grenat_ast.workspace = true

[dev-dependencies]
grenat_parser.workspace = true
