//! The Grenat declarations a library stands for, written from its
//! manifest: its structs, and a `native def` per function —
//!
//! ```ruby
//! ## Reads a sheet.
//! native def read_sheet(path: String) -> ~Array(Array(String)) uses fs.read
//!
//! native def add(a: Int, b: Int) -> Int pure
//! ```
//!
//! A function's result is untrusted (`~T`) unless it is `pure`. What the
//! manifest says is checked before it becomes code: names, types and
//! effects have the shapes Grenat gives them, so that nothing else can
//! slip into the file.

use grenat_ext::manifest::{Field, Function, Manifest, Struct};

/// The declarations of the library of `facet`, described by `manifest`.
pub fn declarations(facet: &str, manifest: &Manifest) -> Result<String, String> {
    let header = format!(
        "# Generated by setter from the native library of the facet `{facet}`: do not edit.\n\
         # Its functions run as Rust code, outside Grenat's sandbox.\n"
    );
    declarations_under(&header, manifest)
}

/// The declarations `manifest` stands for, after `header` (comment lines,
/// trusted): those of a library, or of a bridge facet, whose process
/// describes itself with the same manifest (see `grenat_bridge`).
pub fn declarations_under(header: &str, manifest: &Manifest) -> Result<String, String> {
    let mut out = header.to_string();
    for s in &manifest.structs {
        out.push('\n');
        declare_struct(&mut out, s)?;
    }
    for f in &manifest.functions {
        out.push('\n');
        declare_function(&mut out, f)?;
    }
    Ok(out)
}

fn declare_struct(out: &mut String, s: &Struct) -> Result<(), String> {
    if !is_type_name(&s.name) {
        return Err(format!("the manifest declares a struct named `{}`: not a Grenat type name", s.name));
    }
    doc(out, s.doc.as_deref(), "");
    out.push_str(&format!("struct {}\n", s.name));
    for field in &s.fields {
        doc(out, field.doc.as_deref(), "  ");
        out.push_str(&format!("  {}\n", typed(field, &s.name)?));
    }
    out.push_str("end\n");
    Ok(())
}

fn declare_function(out: &mut String, f: &Function) -> Result<(), String> {
    let line = signature(f)?;
    doc(out, f.doc.as_deref(), "");
    out.push_str(&line);
    out.push('\n');
    Ok(())
}

/// The `native def` line `f` stands for, checked: `native def add(a: Int,
/// b: Int) -> Int pure`. A program's declaration of `f` must be this one
/// (see `grenat_interp`), else it is not bound to `f`.
pub fn signature(f: &Function) -> Result<String, String> {
    if !is_name(&f.name) {
        return Err(format!("the manifest declares a function named `{}`: not a Grenat name", f.name));
    }
    let mut out = format!("native def {}", f.name);
    if !f.params.is_empty() {
        let params: Vec<String> = f.params.iter().map(|p| typed(p, &f.name)).collect::<Result<_, _>>()?;
        out.push_str(&format!("({})", params.join(", ")));
    }
    if !is_type(&f.returns) {
        return Err(format!("`{}` returns `{}`: not a Grenat type", f.name, f.returns));
    }
    match (f.returns.as_str(), f.pure) {
        ("Nil", _) => {}
        (ty, true) => out.push_str(&format!(" -> {ty}")),
        (ty, false) => out.push_str(&format!(" -> ~{ty}")),
    }
    if f.pure && !f.effects.is_empty() {
        return Err(format!("`{}` is pure, and has effects: a pure function has none", f.name));
    }
    if let Some(bad) = f.effects.iter().find(|e| !is_effect(e)) {
        return Err(format!("`{}` has the effect `{bad}`: not a Grenat effect", f.name));
    }
    if !f.effects.is_empty() {
        out.push_str(&format!(" uses {}", f.effects.join(", ")));
    }
    if f.pure {
        out.push_str(" pure");
    }
    Ok(out)
}

/// `name: Type`, both checked.
fn typed(field: &Field, owner: &str) -> Result<String, String> {
    if !is_name(&field.name) {
        return Err(format!("`{owner}` has a field or parameter named `{}`: not a Grenat name", field.name));
    }
    if !is_type(&field.ty) {
        return Err(format!("`{owner}.{}` has the type `{}`: not a Grenat type", field.name, field.ty));
    }
    Ok(format!("{}: {}", field.name, field.ty))
}

/// `##` lines, indented.
fn doc(out: &mut String, doc: Option<&str>, indent: &str) {
    for line in doc.into_iter().flat_map(str::lines) {
        let line = line.trim_end();
        if line.is_empty() {
            out.push_str(&format!("{indent}##\n"));
        } else {
            out.push_str(&format!("{indent}## {line}\n"));
        }
    }
}

/// A Grenat name: `read_sheet`.
fn is_name(name: &str) -> bool {
    name.starts_with(|c: char| c.is_ascii_lowercase() || c == '_')
        && name.chars().all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_')
}

/// A Grenat type name: `Cell`, `SheetError`.
pub fn is_type_name(name: &str) -> bool {
    name.starts_with(|c: char| c.is_ascii_uppercase()) && name.chars().all(|c| c.is_ascii_alphanumeric())
}

/// A Grenat type: `Int`, `Cell?`, `Array(Array(String))`, `Hash(String, Float)`.
fn is_type(text: &str) -> bool {
    let mut rest = text;
    parse_type(&mut rest) && rest.is_empty()
}

fn parse_type(rest: &mut &str) -> bool {
    let end = rest.find(|c: char| !c.is_ascii_alphanumeric()).unwrap_or(rest.len());
    if !is_type_name(&rest[..end]) {
        return false;
    }
    *rest = &rest[end..];
    if let Some(args) = rest.strip_prefix('(') {
        *rest = args;
        loop {
            if !parse_type(rest) {
                return false;
            }
            if let Some(next) = rest.strip_prefix(", ") {
                *rest = next;
            } else if let Some(next) = rest.strip_prefix(')') {
                *rest = next;
                break;
            } else {
                return false;
            }
        }
    }
    if let Some(next) = rest.strip_prefix('?') {
        *rest = next;
    }
    true
}

/// `fs.read`, or `net("api.x.com")`.
fn is_effect(effect: &str) -> bool {
    let (path, restriction) = match effect.split_once('(') {
        Some((path, rest)) => (path, Some(rest)),
        None => (effect, None),
    };
    let path_ok = path.split('.').all(|part| !part.is_empty() && part.chars().all(|c| c.is_ascii_lowercase()));
    let restriction_ok = restriction.is_none_or(|rest| {
        rest.strip_suffix(')')
            .and_then(|quoted| quoted.strip_prefix('"')?.strip_suffix('"'))
            .is_some_and(|inner| !inner.is_empty() && !inner.contains(['"', '\\', '\n', '#']))
    });
    path_ok && restriction_ok
}

#[cfg(test)]
mod tests {
    use super::*;
    use grenat_ext::abi::ABI_VERSION;

    fn field(name: &str, ty: &str) -> Field {
        Field { name: name.into(), ty: ty.into(), doc: None }
    }

    fn function(name: &str, params: Vec<Field>, returns: &str, effects: &[&str], pure: bool) -> Function {
        Function {
            name: name.into(),
            symbol: format!("grenat_ext_v1_{name}"),
            doc: None,
            params,
            returns: returns.into(),
            effects: effects.iter().map(|e| e.to_string()).collect(),
            pure,
            error: "NativeError".into(),
        }
    }

    fn manifest(functions: Vec<Function>, structs: Vec<Struct>) -> Manifest {
        Manifest { abi: ABI_VERSION, functions, structs }
    }

    #[test]
    fn functions_and_structs_are_declared() {
        let cell = Struct {
            name: "Cell".into(),
            doc: Some("A cell.\n\nOf a sheet.".into()),
            fields: vec![Field { doc: Some("From 0.".into()), ..field("row", "Int") }, field("text", "String?")],
        };
        let read = Function {
            doc: Some("Reads a sheet.".into()),
            ..function("read_sheet", vec![field("path", "String")], "Array(Array(String))", &["fs.read"], false)
        };
        let add = function("add", vec![field("a", "Int"), field("b", "Int")], "Int", &[], true);
        let tick = function("tick", vec![], "Nil", &["time", "net(\"api.x.com\")"], false);
        let text = declarations("sheets", &manifest(vec![add, read, tick], vec![cell])).unwrap();
        let expected = "\
# Generated by setter from the native library of the facet `sheets`: do not edit.
# Its functions run as Rust code, outside Grenat's sandbox.

## A cell.
##
## Of a sheet.
struct Cell
  ## From 0.
  row: Int
  text: String?
end

native def add(a: Int, b: Int) -> Int pure

## Reads a sheet.
native def read_sheet(path: String) -> ~Array(Array(String)) uses fs.read

native def tick uses time, net(\"api.x.com\")
";
        assert_eq!(text, expected);
    }

    #[test]
    fn what_is_not_grenat_is_refused() {
        let err = |f: Function| declarations("x", &manifest(vec![f], vec![])).unwrap_err();
        assert!(err(function("Add", vec![], "Int", &[], true)).contains("not a Grenat name"));
        assert!(err(function("f\nnative def g", vec![], "Int", &[], true)).contains("not a Grenat name"));
        assert!(err(function("f", vec![field("x", "Int) = 1")], "Int", &[], true)).contains("not a Grenat type"));
        assert!(err(function("f", vec![field("X", "Int")], "Int", &[], true)).contains("not a Grenat name"));
        assert!(err(function("f", vec![], "Array(Int", &[], true)).contains("not a Grenat type"));
        assert!(err(function("f", vec![], "Int", &["fs read"], false)).contains("not a Grenat effect"));
        assert!(err(function("f", vec![], "Int", &["net(\"a\")\nx"], false)).contains("not a Grenat effect"));
        assert!(err(function("f", vec![], "Int", &["net"], true)).contains("a pure function has none"));
        let bad_struct = Struct { name: "cell".into(), doc: None, fields: vec![] };
        assert!(declarations("x", &manifest(vec![], vec![bad_struct])).unwrap_err().contains("not a Grenat type name"));
    }

    #[test]
    fn types_have_grenat_shapes() {
        for ok in ["Int", "Cell?", "Array(Array(String))", "Hash(String, Array(Float?))", "Result(Int, String)"] {
            assert!(is_type(ok), "{ok}");
        }
        for bad in ["", "int", "Array(", "Array()", "Hash(String,Int)", "Int??", "~Int", "Int x"] {
            assert!(!is_type(bad), "{bad}");
        }
    }
}
