//! Release builds through LLVM (`grenat build --release`).
//!
//! The front end is the same as for Cranelift: [`LlvmModule`] is a
//! `cranelift_module::Module` that records the Cranelift IR of every
//! function and the contents of every data object, instead of compiling
//! them. [`LlvmModule::finish`] translates the whole module into LLVM IR
//! (`function`, `data`), which `clang -O3` optimizes and compiles into an
//! object file (`compile`). One front end, two back ends: Cranelift for
//! fast builds and the JIT, LLVM for the fastest code.

mod compile;
mod data;
mod function;
mod names;

use cranelift_codegen::ir::{self, Function};
use cranelift_codegen::isa::{OwnedTargetIsa, TargetIsa};
use cranelift_codegen::{Context, control::ControlPlane};
use cranelift_module::{
    DataDescription, DataId, FuncId, Linkage, Module, ModuleDeclarations, ModuleError, ModuleResult,
};

pub use compile::{clang, compile};

pub struct LlvmModule {
    isa: OwnedTargetIsa,
    declarations: ModuleDeclarations,
    functions: Vec<(FuncId, Function)>,
    data: Vec<(DataId, DataDescription)>,
}

impl LlvmModule {
    pub fn new(isa: OwnedTargetIsa) -> LlvmModule {
        LlvmModule { isa, declarations: ModuleDeclarations::default(), functions: Vec::new(), data: Vec::new() }
    }

    /// The module in LLVM IR; an error names what cannot be translated.
    pub fn finish(self) -> Result<String, String> {
        let names = names::Names::new(&self.declarations);
        let mut ir = String::from("; Generated by grenat from Cranelift IR.\n\n");
        let mut intrinsics = std::collections::BTreeSet::new();
        let defined: std::collections::HashSet<FuncId> = self.functions.iter().map(|(id, _)| *id).collect();
        for (id, decl) in self.declarations.get_functions() {
            if !defined.contains(&id) {
                ir.push_str(&format!("declare {}\n", function::prototype(&names.function(id), &decl.signature, None)?));
            }
        }
        let data_defined: std::collections::HashSet<DataId> = self.data.iter().map(|(id, _)| *id).collect();
        for (id, _) in self.declarations.get_data_objects() {
            if !data_defined.contains(&id) {
                ir.push_str(&format!("{} = external global i8\n", names.data(id)));
            }
        }
        ir.push('\n');
        for (id, description) in &self.data {
            let decl = self.declarations.get_data_decl(*id);
            ir.push_str(&data::global(&names, *id, decl, description)?);
        }
        for (id, func) in &self.functions {
            let decl = self.declarations.get_function_decl(*id);
            let linkage = names::linkage(decl.linkage);
            ir.push('\n');
            ir.push_str(&function::define(&names, &names.function(*id), linkage, func, &mut intrinsics)?);
        }
        ir.push('\n');
        for intrinsic in intrinsics {
            ir.push_str(&intrinsic);
            ir.push('\n');
        }
        ir.push_str("\nattributes #0 = { nounwind }\n");
        Ok(ir)
    }
}

impl Module for LlvmModule {
    fn isa(&self) -> &dyn TargetIsa {
        &*self.isa
    }

    fn declarations(&self) -> &ModuleDeclarations {
        &self.declarations
    }

    fn declare_function(&mut self, name: &str, linkage: Linkage, signature: &ir::Signature) -> ModuleResult<FuncId> {
        self.declarations.declare_function(name, linkage, signature).map(|(id, _)| id)
    }

    fn declare_anonymous_function(&mut self, signature: &ir::Signature) -> ModuleResult<FuncId> {
        self.declarations.declare_anonymous_function(signature)
    }

    fn declare_data(&mut self, name: &str, linkage: Linkage, writable: bool, tls: bool) -> ModuleResult<DataId> {
        self.declarations.declare_data(name, linkage, writable, tls).map(|(id, _)| id)
    }

    fn declare_anonymous_data(&mut self, writable: bool, tls: bool) -> ModuleResult<DataId> {
        self.declarations.declare_anonymous_data(writable, tls)
    }

    fn define_function_with_control_plane(
        &mut self,
        func: FuncId,
        ctx: &mut Context,
        _ctrl_plane: &mut ControlPlane,
    ) -> ModuleResult<()> {
        self.functions.push((func, ctx.func.clone()));
        Ok(())
    }

    fn define_function_bytes(
        &mut self,
        _func: FuncId,
        _alignment: u64,
        _bytes: &[u8],
        _relocs: &[cranelift_module::ModuleReloc],
    ) -> ModuleResult<()> {
        Err(ModuleError::Undeclared("machine code cannot be translated to LLVM IR".into()))
    }

    fn define_data(&mut self, data: DataId, description: &DataDescription) -> ModuleResult<()> {
        self.data.push((data, description.clone()));
        Ok(())
    }
}
