//! Installing a facet's bridge: the helper libraries written into the
//! facet, its server started once (without the network) to `describe`
//! itself, and what it answers — the manifest of a native library — kept
//! next to the `native def` declarations it stands for.

use std::path::{Path, PathBuf};

use grenat_native::Manifest;
use grenat_native::declarations::declarations_under;

use crate::bridge::Bridge;
use crate::helpers;
use crate::layout::Layout;
use crate::protocol::PROTOCOL_VERSION;
use crate::spec::Spec;

/// A facet's bridge, as installed.
#[derive(Debug, Clone, PartialEq)]
pub struct Installed {
    pub facet: String,
    /// The facet's directory, where its server runs.
    pub dir: PathBuf,
    pub spec: Spec,
    pub manifest: Manifest,
}

impl Installed {
    /// The bridge installed in the facet `facet`'s directory `dir` (what
    /// `setter install` wrote there).
    pub fn read(facet: &str, dir: &Path, spec: &Spec) -> Result<Installed, String> {
        let path = Layout::new(dir).manifest();
        let text = std::fs::read_to_string(&path)
            .map_err(|_| format!("the bridge of facet `{facet}` is not installed: run `setter install`"))?;
        let manifest = serde_json::from_str(&text).map_err(|e| format!("{}: {e}", path.display()))?;
        Ok(Installed { facet: facet.to_string(), dir: dir.to_path_buf(), spec: spec.clone(), manifest })
    }
}

/// Installs the bridge of the facet `facet` in `dir`, started by `spec`.
pub fn install(facet: &str, dir: &Path, spec: &Spec) -> Result<Installed, String> {
    let layout = Layout::new(dir);
    helpers::write(&layout.lib())?;
    let answer = Bridge::new(facet, dir, spec, false, None).describe()?;
    let manifest = manifest(facet, answer)?;
    let header = format!(
        "# Generated by setter from the bridge of the facet `{facet}`: do not edit.\n\
         # Its functions run in a process of their own, outside Grenat's sandbox.\n"
    );
    let declarations = declarations_under(&header, &manifest)?;
    write(&layout.manifest(), &serde_json::to_string_pretty(&manifest).expect("a manifest is JSON"))?;
    write(&layout.declarations(), &declarations)?;
    Ok(Installed { facet: facet.to_string(), dir: dir.to_path_buf(), spec: spec.clone(), manifest })
}

/// The manifest a server answered, checked: the protocol's version, and a
/// name exported once.
fn manifest(facet: &str, answer: serde_json::Value) -> Result<Manifest, String> {
    let abi = answer.get("abi").and_then(serde_json::Value::as_u64);
    if abi != Some(u64::from(PROTOCOL_VERSION)) {
        return Err(format!(
            "the process of facet `{facet}` speaks version {} of the bridge protocol, and this Grenat speaks version \
             {PROTOCOL_VERSION}: update its helper library",
            abi.map_or("?".to_string(), |v| v.to_string())
        ));
    }
    let manifest: Manifest = serde_json::from_value(answer)
        .map_err(|e| format!("the process of facet `{facet}` describes itself wrongly: {e}"))?;
    let mut names = std::collections::HashSet::new();
    if let Some(twice) = manifest.functions.iter().find(|f| !names.insert(f.name.as_str())) {
        return Err(format!("the process of facet `{facet}` exports `{}` twice", twice.name));
    }
    Ok(manifest)
}

fn write(path: &Path, text: &str) -> Result<(), String> {
    if let Some(dir) = path.parent() {
        std::fs::create_dir_all(dir).map_err(|e| format!("cannot create {}: {e}", dir.display()))?;
    }
    std::fs::write(path, text).map_err(|e| format!("cannot write {}: {e}", path.display()))
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn a_manifest_is_checked() {
        let function = |name: &str| {
            json!({"name": name, "symbol": name, "doc": null, "params": [], "returns": "Int", "effects": [],
                   "pure": true, "error": "BridgeError"})
        };
        let ok = manifest("t", json!({"abi": 1, "functions": [function("a")], "structs": []})).unwrap();
        assert_eq!(ok.functions[0].name, "a");
        let e = manifest("t", json!({"abi": 2, "functions": [], "structs": []})).unwrap_err();
        assert!(e.contains("speaks version 2 of the bridge protocol"), "{e}");
        let e = manifest("t", json!({"functions": []})).unwrap_err();
        assert!(e.contains("speaks version ? of the bridge protocol"), "{e}");
        let e = manifest("t", json!({"abi": 1, "functions": [{"name": "a"}], "structs": []})).unwrap_err();
        assert!(e.starts_with("the process of facet `t` describes itself wrongly"), "{e}");
        let twice = json!({"abi": 1, "functions": [function("a"), function("a")], "structs": []});
        assert_eq!(manifest("t", twice).unwrap_err(), "the process of facet `t` exports `a` twice");
    }

    #[test]
    fn a_bridge_not_installed_says_so() {
        let e = Installed::read("t", Path::new("/nowhere"), &Spec::new(&["ruby"])).unwrap_err();
        assert_eq!(e, "the bridge of facet `t` is not installed: run `setter install`");
    }
}
