[package]
name = "grenat_cli"
description = "Compiler and command-line tools for the Grenat language"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "grenat"
path = "src/main.rs"

[dependencies]
grenat_lexer.workspace = true
grenat_ast.workspace = true
grenat_parser.workspace = true
grenat_interp.workspace = true
grenat_types.workspace = true
grenat_driver.workspace = true
grenat_codegen.workspace = true
